const municipalities = require('../../models/municipalities.models')

municipalities.bulkCreate([
    {id:33, name:'Azua de Compostela', parent:1},
    {id:34, name:'Estebanía', parent:1},
    {id:35, name:'Guayabal', parent:1},
    {id:36, name:'Las Charcas', parent:1},
    {id:37, name:'Las Yayas de Viajama', parent:1},
    {id:38, name:'Padre Las Casas', parent:1},
    {id:39, name:'Peralta', parent:1},
    {id:40, name:'Pueblo Viejo', parent:1},
    {id:41, name:'Sabana Yegua', parent:1},
    {id:42, name:'Tábara Arriba', parent:1},
    {id:43, name:'Neiba', parent:2},
    {id:44, name:'Galván', parent:2},
    {id:45, name:'Los Ríos', parent:2},
    {id:46, name:'Tamayo', parent:2},
    {id:47, name:'Villa Jaragua', parent:2},
    {id:48, name:'Barahona', parent:3},
    {id:49, name:'Cabral', parent:3},
    {id:50, name:'El Peñón', parent:3},
    {id:51, name:'Enriquillo', parent:3},
    {id:52, name:'Fundación', parent:3},
    {id:53, name:'Jaquimeyes', parent:3},
    {id:54, name:'La Ciénaga', parent:3},
    {id:55, name:'Las Salinas', parent:3},
    {id:56, name:'Paraíso', parent:3},
    {id:57, name:'Polo', parent:3},
    {id:58, name:'Vicente Noble', parent:3},
    {id:59, name:'Dajabón', parent:4},
    {id:60, name:'El Pino', parent:4},
    {id:61, name:'Loma de Cabrera', parent:4},
    {id:62, name:'Partido', parent:4},
    {id:63, name:'Restauración', parent:4},
    {id:64, name:'San Francisco de Macorís', parent:5},
    {id:65, name:'Arenoso', parent:5},
    {id:66, name:'Castillo', parent:5},
    {id:67, name:'Eugenio María de Hostos', parent:5},
    {id:68, name:'Las Guáranas', parent:5},
    {id:69, name:'Pimentel', parent:5},
    {id:70, name:'Villa Riva', parent:5},
    {id:71, name:'Comendador', parent:6},
    {id:72, name:'Bánica', parent:6},
    {id:73, name:'El Llano', parent:6},
    {id:74, name:'Hondo Valle', parent:6},
    {id:75, name:'Juan Santiago', parent:6},
    {id:76, name:'Pedro Santana', parent:6},
    {id:77, name:'El Seibo', parent:7},
    {id:78, name:'Miches', parent:7},
    {id:79, name:'Moca', parent:8},
    {id:80, name:'Cayetano Germosén', parent:8},
    {id:81, name:'Gaspar Hernández', parent:8},
    {id:82, name:'Jamao al Norte', parent:8},
    {id:83, name:'Hato Mayor del Rey', parent:9},
    {id:84, name:'El Valle', parent:9},
    {id:85, name:'Sabana de la Mar', parent:9},
    {id:86, name:'Salcedo', parent:10},
    {id:87, name:'Tenares', parent:10},
    {id:88, name:'Villa Tapia', parent:10},
    {id:89, name:'Jimaní', parent:11},
    {id:90, name:'Cristóbal', parent:11},
    {id:91, name:'Duvergé', parent:11},
    {id:92, name:'La Descubierta', parent:11},
    {id:93, name:'Mella', parent:11},
    {id:94, name:'Postrer Río', parent:11},
    {id:95, name:'Higüey', parent:12},
    {id:96, name:'San Rafael del Yuma', parent:12},
    {id:97, name:'La Romana', parent:13},
    {id:98, name:'Guaymate', parent:13},
    {id:99, name:'Villa Hermosa', parent:13},
    {id:100, name:'La Concepción de La Vega', parent:14},
    {id:101, name:'Constanza', parent:14},
    {id:102, name:'Jarabacoa', parent:14},
    {id:103, name:'Jima Abajo', parent:14},
    {id:104, name:'Nagua', parent:15},
    {id:105, name:'Cabrera', parent:15},
    {id:106, name:'El Factor', parent:15},
    {id:107, name:'Río San Juan', parent:15},
    {id:108, name:'Bonao', parent:16},
    {id:109, name:'Maimón', parent:16},
    {id:110, name:'Piedra Blanca', parent:16},
    {id:111, name:'Montecristi', parent:17},
    {id:112, name:'Castañuela', parent:17},
    {id:113, name:'Guayubín', parent:17},
    {id:114, name:'Las Matas de Santa Cruz', parent:17},
    {id:115, name:'Pepillo Salcedo', parent:17},
    {id:116, name:'Villa Vásquez', parent:17},
    {id:117, name:'Monte Plata', parent:18},
    {id:118, name:'Bayaguana', parent:18},
    {id:119, name:'Peralvillo', parent:18},
    {id:120, name:'Sabana Grande de Boyá', parent:18},
    {id:121, name:'Yamasá', parent:18},
    {id:122, name:'Pedernales', parent:19},
    {id:123, name:'Oviedo', parent:19},
    {id:124, name:'Baní', parent:20},
    {id:125, name:'Nizao', parent:20},
    {id:126, name:'Puerto Plata', parent:21},
    {id:127, name:'Altamira', parent:21},
    {id:128, name:'Guananico', parent:21},
    {id:129, name:'Imbert', parent:21},
    {id:130, name:'Los Hidalgos', parent:21},
    {id:131, name:'Luperón', parent:21},
    {id:132, name:'Sosúa', parent:21},
    {id:133, name:'Villa Isabela', parent:21},
    {id:134, name:'Villa Montellano', parent:21},
    {id:135, name:'Samaná', parent:22},
    {id:136, name:'Las Terrenas', parent:22},
    {id:137, name:'Sánchez', parent:22},
    {id:138, name:'San Cristóbal', parent:23},
    {id:139, name:'Bajos de Haina', parent:23},
    {id:140, name:'Cambita Garabito', parent:23},
    {id:141, name:'Los Cacaos', parent:23},
    {id:142, name:'Sabana Grande de Palenque', parent:23},
    {id:143, name:'San Gregorio de Nigua', parent:23},
    {id:144, name:'Villa Altagracia', parent:23},
    {id:145, name:'Yaguate', parent:23},
    {id:146, name:'San José de Ocoa', parent:24},
    {id:147, name:'Rancho Arriba', parent:24},
    {id:148, name:'Sabana Larga', parent:24},
    {id:149, name:'San Juan de la Maguana', parent:25},
    {id:150, name:'Bohechío', parent:25},
    {id:151, name:'El Cercado', parent:25},
    {id:152, name:'Juan de Herrera', parent:25},
    {id:153, name:'Las Matas de Farfán', parent:25},
    {id:154, name:'Vallejuelo', parent:25},
    {id:155, name:'San Pedro de Macorís', parent:26},
    {id:156, name:'Consuelo', parent:26},
    {id:157, name:'Guayacanes', parent:26},
    {id:158, name:'Quisqueya', parent:26},
    {id:159, name:'Ramón Santana', parent:26},
    {id:160, name:'San José de Los Llanos', parent:26},
    {id:161, name:'Cotuí', parent:27},
    {id:162, name:'Cevicos', parent:27},
    {id:163, name:'Fantino', parent:27},
    {id:164, name:'La Mata', parent:27},
    {id:165, name:'Santiago', parent:28},
    {id:166, name:'Bisonó', parent:28},
    {id:167, name:'Jánico', parent:28},
    {id:168, name:'Licey al Medio', parent:28},
    {id:169, name:'Puñal', parent:28},
    {id:170, name:'Sabana Iglesia', parent:28},
    {id:171, name:'San José de las Matas', parent:28},
    {id:172, name:'Tamboril', parent:28},
    {id:173, name:'Villa González', parent:28},
    {id:174, name:'San Ignacio de Sabaneta', parent:29},
    {id:175, name:'Los Almácigos', parent:29},
    {id:176, name:'Monción', parent:29},
    {id:177, name:'Santo Domingo Este', parent:30},
    {id:178, name:'Boca Chica', parent:30},
    {id:179, name:'Los Alcarrizos', parent:30},
    {id:180, name:'Pedro Brand', parent:30},
    {id:181, name:'San Antonio de Guerra', parent:30},
    {id:182, name:'Santo Domingo Norte', parent:30},
    {id:183, name:'Santo Domingo Oeste', parent:30},
    {id:184, name:'Mao', parent:31},
    {id:185, name:'Esperanza', parent:31},
    {id:186, name:'Laguna Salada', parent:31},
    {id:187, name:'Distrito Nacional', parent:32},
])
