const Provinces = require('../../models/provinces.models')

Provinces.bulkCreate([
{id:1, name:'Azua', parent:0},
{id:2, name:'Baoruco', parent:0},
{id:3, name:'Barahona', parent:0},
{id:4, name:'Dajabón', parent:0},
{id:5, name:'Duarte', parent:0},
{id:6, name:'Elías Piña', parent:0},
{id:7, name:'El Seibo', parent:0},
{id:8, name:'Espaillat', parent:0},
{id:9, name:'Hato Mayor', parent:0},
{id:10, name:'Hermanas Mirabal', parent:0},
{id:11, name:'Independencia', parent:0},
{id:12, name:'La Altagracia', parent:0},
{id:13, name:'La Romana', parent:0},
{id:14, name:'La Vega', parent:0},
{id:15, name:'María Trinidad Sánchez', parent:0},
{id:16, name:'Monseñor Nouel', parent:0},
{id:17, name:'Montecristi', parent:0},
{id:18, name:'Monte Plata', parent:0},
{id:19, name:'Pedernales', parent:0},
{id:20, name:'Peravia', parent:0},
{id:21, name:'Puerto Plata', parent:0},
{id:22, name:'Samaná', parent:0},
{id:23, name:'San Cristóbal', parent:0},
{id:24, name:'San José de Ocoa', parent:0},
{id:25, name:'San Juan', parent:0},
{id:26, name:'San Pedro de Macorís', parent:0},
{id:27, name:'Sánchez Ramírez', parent:0},
{id:28, name:'Santiago', parent:0},
{id:29, name:'Santiago Rodríguez', parent:0},
{id:30, name:'Santo Domingo', parent:0},
{id:31, name:'Valverde', parent:0},
{id:32, name:'Distrito Nacional', parent:0}
])
